remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Recipe Ratings & Saturated Fat Analysis
description: Analyzing the relationship between sat fat amounts and recipe ratings.
